# Generated by Django 4.0.3 on 2022-03-20 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payments',
            name='seller_customer',
        ),
        migrations.RemoveField(
            model_name='products',
            name='seller',
        ),
        migrations.RemoveField(
            model_name='purchases',
            name='seller_customer',
        ),
        migrations.RemoveField(
            model_name='sellers_customers',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='sellers_customers',
            name='seller',
        ),
        migrations.DeleteModel(
            name='Items',
        ),
        migrations.DeleteModel(
            name='Payments',
        ),
        migrations.DeleteModel(
            name='Products',
        ),
        migrations.DeleteModel(
            name='Purchases',
        ),
        migrations.DeleteModel(
            name='Sellers_Customers',
        ),
    ]
