# Generated by Django 4.0.3 on 2022-03-19 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchases',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='purchases',
            name='state',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
