# Generated by Django 4.0.3 on 2022-03-21 07:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='state',
        ),
        migrations.AddField(
            model_name='purchase',
            name='status',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AlterField(
            model_name='sellercustomer',
            name='seller',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_as_seller', to=settings.AUTH_USER_MODEL),
        ),
    ]
