# Generated by Django 4.0.3 on 2022-03-28 06:40

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0012_alter_product_name'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('seller', 'name')},
        ),
    ]
